// Enhance the existing world; do not replace its React state or browser records.
const BASE='/goober/';
function card(id,title,subtitle,image){const a=document.createElement('a');a.href=BASE+'gallery/#'+id;a.className='world-window';const img=document.createElement('img');img.src=BASE+'assets/rediscovered/'+image;img.alt=title;img.loading='lazy';const copy=document.createElement('span'),b=document.createElement('b'),small=document.createElement('small');b.textContent=title;small.textContent=subtitle;copy.append(b,small);a.append(img,copy);return a;}
function enhance(){const hero=document.querySelector('.hero');let collection=document.getElementById('rediscovered-worlds');if(!hero){collection?.remove();return;}
 if(!hero.dataset.enriched){const im=hero.querySelector('.hero-art');if(im){im.src=BASE+'assets/rediscovered/world-hero.webp';im.alt='Recovered concept: a traveler overlooking a luminous landscape in the earlier Anewgam world';}const credit=hero.querySelector('.art-credit');if(credit){credit.href=BASE+'gallery/#peachfall-03';credit.textContent='Recovered world art · Open the original ↗';}hero.dataset.enriched='true';}
 if(!collection){collection=document.createElement('section');collection.id='rediscovered-worlds';collection.className='rediscovered-worlds';const top=document.createElement('div');top.className='rediscovered-top';const text=document.createElement('div'),k=document.createElement('span'),h=document.createElement('h2'),a=document.createElement('a');k.textContent='THE WORLD IS GETTING BIGGER';k.className='eyebrow';h.textContent='A few more doors just opened.';text.append(k,h);a.href=BASE+'gallery/';a.textContent='Explore all 12 pictures ↗';top.append(text,a);const row=document.createElement('div');row.className='world-windows';row.append(card('peachfall-02','A constellation to collect','Astral assembly','peachfall-02.webp'),card('peachfall-06','Someone at the threshold','Sae and Knight','peachfall-06.webp'),card('peachfall-09','Play makes a place','The world-creation concept','peachfall-09.webp'));const last=document.createElement('p');last.className='rediscovered-last';last.append('Recovered from the earlier Anewgam story. ');const play=document.createElement('a');play.href='/peachfall/';play.textContent='Visit the playable Peachfall doorway →';last.append(play);collection.append(top,row,last);hero.after(collection);}
 const footer=document.querySelector('main footer');if(footer&&!footer.querySelector('[data-lattice]')){const link=document.createElement('a');link.dataset.lattice='true';link.href=BASE+'lattice/';link.textContent='One world · named doorways ◇';footer.append(link);}
}
let queued=false;const app=document.getElementById('app');new MutationObserver(()=>{if(!queued){queued=true;requestAnimationFrame(()=>{queued=false;enhance();});}}).observe(app,{childList:true,subtree:true});enhance();
