const $=id=>document.getElementById(id),KEY='goober.obs-guide.v1';let content,checked=new Set(),storage=true;
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
async function copy(text){try{await navigator.clipboard.writeText(text);$('status').textContent='Copied. Nothing was run or posted.';}catch{$('status').textContent='Clipboard unavailable. Select and copy this text:\n'+text;}}
function progress(){const valid=new Set(content.steps.map(s=>s.id));checked=new Set([...checked].filter(x=>valid.has(x)));$('progress').value=checked.size;$('progress-text').textContent=checked.size+' / 6 marked'+(storage?'':' · not saved');for(const s of document.querySelectorAll('.step')){s.classList.toggle('done',checked.has(s.dataset.id));s.querySelector('input').checked=checked.has(s.dataset.id);}}
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{const portable=b.dataset.mode==='portable';$('app-path').textContent=portable?'%USERPROFILE%\\Apps\\OBS-Portable\\':'C:\\Program Files\\obs-studio\\';$('settings-path').textContent=portable?'Inside this portable copy’s configuration folder':'%APPDATA%\\obs-studio\\';$('mode-note').textContent=portable?'Example only: extract the official ZIP into a writable user folder. Enable Portable mode explicitly. Media and recordings are still separate path choices.':'Typical paths are examples, not a scan of your PC. Inspect an existing OBS shortcut’s Target instead of guessing.';for(const x of document.querySelectorAll('[data-mode]'))x.setAttribute('aria-pressed',String(x===b));};
for(const b of document.querySelectorAll('[data-copy]'))b.onclick=()=>copy($(b.dataset.copy).textContent);
try{const response=await fetch('content.json',{cache:'no-cache'});if(!response.ok)throw Error('Guide content could not be loaded');content=await response.json();if(content.schema!=='saelion.field-guide/0.1'||content.steps.length!==6||content.thread.length!==8)throw Error('Guide format is unavailable');
try{const prior=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(prior))checked=new Set(prior.filter(x=>typeof x==='string'));}catch{storage=false;}
for(const s of content.steps){const item=node('article',undefined,'step');item.id='step-'+s.id;item.dataset.id=s.id;const pic=node('a',undefined,'step-picture');pic.href='cards/'+s.number+'-'+s.id+'.png';pic.target='_blank';pic.rel='noopener';const im=node('img');im.src=pic.href;im.alt=s.card_title+'. '+s.card_body;im.width=1200;im.height=675;im.loading='lazy';pic.append(im);const copybox=node('div',undefined,'step-copy');copybox.append(node('span',s.number+' / '+s.eyebrow,'eyebrow'),node('h3',s.title),node('p',s.copy));const proof=node('div',undefined,'proof');proof.append(node('b','What to check'),document.createTextNode(s.proof));const src=node('a',s.source_label+' ↗','step-source');const u=new URL(s.source);if(u.hostname!=='obsproject.com'||u.protocol!=='https:')throw Error('Unexpected source');src.href=u.href;src.target='_blank';src.rel='noopener noreferrer';const label=node('label',undefined,'check-control');const check=node('input');check.type='checkbox';check.setAttribute('aria-label','Mark step '+s.number+' checked');check.onchange=()=>{check.checked?checked.add(s.id):checked.delete(s.id);try{localStorage.setItem(KEY,JSON.stringify([...checked]));storage=true;}catch{storage=false;$('status').textContent='Browser storage is unavailable. Your checkmarks are not saved.';}progress();};label.append(check,document.createTextNode('I checked this on my PC'));copybox.append(proof,src,label);item.append(pic,copybox);$('steps').append(item);
const fig=node('figure',undefined,'share-card');const a=node('a');a.href=pic.href;a.target='_blank';a.rel='noopener';const thumb=im.cloneNode();thumb.loading='lazy';a.append(thumb);const caption=node('figcaption',s.number+' / '+s.card_title);const save=node('a','Save PNG ↓');save.href=pic.href;save.download=s.number+'-'+s.id+'.png';fig.append(a,caption,save);$('share-cards').append(fig);}
$('narration').textContent=content.narration;$('copy-narration').onclick=()=>copy(content.narration);$('copy-thread').onclick=()=>copy(content.thread.join('\n\n'));
content.thread.forEach((text,i)=>{const entry=node('article',undefined,'post');const b=node('button','Copy post '+(i+1));b.onclick=()=>copy(text);entry.append(node('p',text),b,node('small',text.length+' characters'));$('posts').append(entry);});for(const s of content.sources){const a=node('a',s.title+' ↗');a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';$('sources').append(a);}progress();document.body.dataset.ready='true';if(location.hash.startsWith('#step-'))document.querySelector(location.hash)?.scrollIntoView();
}catch(error){$('status').textContent=error.message+'. Use the plain-text walkthrough or official sources.';}
