'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),n=require('./nougat.js');
const t=(...types)=>types.map(type=>({type}));
test('princess starts without invented history',()=>assert.deepEqual(n.initial(),{role:'princess',woven:false,lit:false,gift:false,crossed:false,ended:false}));
test('at least one actual path before handoff',()=>assert.throws(()=>n.replay(t('gift','handoff'))));
test('bridge route preserves gift',()=>assert.deepEqual(n.replay(t('weave','gift','handoff','cross','share')),{role:'knight',woven:true,lit:false,gift:true,crossed:true,ended:true}));
test('lantern route is a real alternative',()=>assert.equal(n.replay(t('light','handoff','cross','rest')).ended,true));
test('source state is not mutated',()=>{const s=n.initial();n.transition(s,'weave');assert.equal(s.woven,false);});
test('repeat actions rejected',()=>assert.throws(()=>n.replay(t('weave','weave'))));
test('knight cannot retroactively create a gift',()=>assert.throws(()=>n.replay(t('weave','handoff','gift'))));
test('cannot share a nonexistent nougat',()=>assert.throws(()=>n.replay(t('weave','handoff','cross','share'))));
test('no actions after ending',()=>assert.deepEqual(n.allowed(n.replay(t('light','gift','handoff','cross','share'))),[]));
test('export import preserves exact actions',()=>{const e=t('light','gift','handoff');assert.deepEqual(n.unpack(JSON.stringify(n.pack(e))),e);});
test('rejects extra data and authority fields',()=>assert.throws(()=>n.unpack(JSON.stringify({schema:n.SCHEMA,events:[],authority:'root'}))));
test('rejects excess events',()=>assert.throws(()=>n.replay(Array(8).fill({type:'weave'}))));
test('rejects malformed event',()=>assert.throws(()=>n.replay([{type:'weave',extra:1}])));
test('rejects arbitrary action',()=>assert.throws(()=>n.replay(t('launch_shell'))));
test('rejects oversized import',()=>assert.throws(()=>n.unpack(' '.repeat(32769))));
test('request contains only fictional enum state',()=>{const r=n.requestFor(n.initial(),'fixture');assert.equal(r.state.role,'princess');assert.equal(Object.hasOwn(r.state,'threads'),false);assert.equal(Object.hasOwn(r.state,'image'),false);assert.deepEqual(Object.keys(r.questions.next.criteria),['weave','light','gift','skip']);});
const request=n.requestFor(n.initial(),'fixture');
const response=()=>({model:'fixture',answers:{next:{type:'choice',choice:'gift',probabilities:{weave:.1,light:.1,gift:.7,skip:.1}}}});
test('accepts full coherent distribution',()=>assert.equal(n.validateAdvice(request,response()).choice,'gift'));
test('rejects wrong model',()=>{const r=response();r.model='other';assert.throws(()=>n.validateAdvice(request,r));});
test('rejects invented choice',()=>{const r=response();r.answers.next.choice='root';assert.throws(()=>n.validateAdvice(request,r));});
test('rejects missing probability',()=>{const r=response();delete r.answers.next.probabilities.skip;assert.throws(()=>n.validateAdvice(request,r));});
test('rejects nonfinite score',()=>{const r=response();r.answers.next.probabilities.gift=NaN;assert.throws(()=>n.validateAdvice(request,r));});
test('rejects contradictory selection',()=>{const r=response();r.answers.next.choice='weave';assert.throws(()=>n.validateAdvice(request,r));});
test('rejects wrong total',()=>{const r=response();r.answers.next.probabilities.gift=.6;assert.throws(()=>n.validateAdvice(request,r));});
test('completed story needs no model',()=>assert.throws(()=>n.requestFor(n.replay(t('weave','handoff','cross','rest')),'fixture')));
test('all reachable states replay and have bounded histories',()=>{let count=0;function visit(events){const s=n.replay(events);count++;assert.deepEqual(n.unpack(JSON.stringify(n.pack(events))),events);for(const a of n.allowed(s))visit([...events,{type:a}]);}visit([]);assert.ok(count>50);console.log('Reachable prefixes verified:',count);});
