const $=id=>document.getElementById(id),viewer=$('viewer'),tiles=[...document.querySelectorAll('.tile')];
let items=[],current=0,room='all',preview=false,zoom=1,pan={x:0,y:0},drag=null;
function asset(value){const u=new URL(value,location.href);if(u.origin!==location.origin||!['/goober/assets/','/peachfall/source/images/'].some(p=>u.pathname.startsWith(p)))throw Error('Unexpected artwork path');return u.href;}
function selection(){const q=$('search').value.trim().toLowerCase();return items.filter(a=>(room==='all'||a.room===room)&&(a.title+' '+a.description+' '+a.source_filename+' '+a.id).toLowerCase().includes(q));}
function filter(){const ids=new Set(selection().map(a=>a.id));for(const t of tiles)t.hidden=!ids.has(t.dataset.id);$('count').textContent=ids.size+' of '+items.length+' original artworks';$('empty').hidden=ids.size>0;}
function shape(){const s=$('stage'),im=$('large');if(!im.naturalWidth)return;const scale=Math.min((s.clientWidth-20)/im.naturalWidth,(s.clientHeight-20)/im.naturalHeight,1);im.style.width=Math.max(1,im.naturalWidth*scale)+'px';im.style.height=Math.max(1,im.naturalHeight*scale)+'px';im.style.transform=`translate(-50%,-50%) translate(${pan.x}px,${pan.y}px) scale(${zoom})`;$('reset').textContent=Math.round(zoom*100)+'%';}
function reset(){zoom=1;pan={x:0,y:0};shape();}
function paint(){const a=items[current];$('art-title').textContent=a.title;$('position').textContent=`${current+1} / ${items.length} · ${a.id}`;$('room-label').textContent=a.room;$('description').textContent=a.description;$('filename').textContent=a.source_filename;$('large').src=asset(preview?a.preview_url:a.original_url);$('large').alt=a.title;$('original').href=asset(a.original_url);$('variant').textContent=preview?'Show original':'Show preview';$('preview-state').textContent=preview?'Recorded preview derivative':'Full original · no catalog crop';$('evidence').textContent=JSON.stringify({id:a.id,title_status:a.title_status,source:a.source_kind,filename:a.source_filename,sha256:a.original_sha256,bytes:a.original_bytes,transformation:a.transformation},null,2);$('status').textContent='';$('cdn').hidden=!a.cloudfront_original;if(a.cloudfront_original)$('cdn').href=a.cloudfront_original;for(const b of $('filmstrip').children)b.setAttribute('aria-current',String(b.dataset.id===a.id));reset();}
function open(id,update=true){const i=items.findIndex(a=>a.id===id);if(i<0)return;current=i;preview=false;paint();if(!viewer.open)viewer.showModal();document.body.classList.add('viewing');shape();if(update)history.replaceState(null,'','#'+id);}
function step(d){const list=selection().length?selection():items;const i=list.findIndex(a=>a.id===items[current].id);open(list[(i+d+list.length)%list.length].id);}
function close(){viewer.close();document.body.classList.remove('viewing');if(items.some(a=>location.hash==='#'+a.id))history.replaceState(null,'',location.pathname+location.search);}
function changeZoom(d){zoom=Math.max(1,Math.min(5,zoom+d));if(zoom===1)pan={x:0,y:0};shape();}
for(const a of document.querySelectorAll('[data-art]'))a.addEventListener('click',e=>{if(items.length&&!e.metaKey&&!e.ctrlKey&&!e.shiftKey){e.preventDefault();open(a.dataset.art);}});
for(const b of document.querySelectorAll('.rooms button'))b.onclick=()=>{room=b.dataset.room;for(const x of document.querySelectorAll('.rooms button'))x.setAttribute('aria-pressed',String(x===b));filter();};
$('search').oninput=filter;$('density').onchange=()=>$('wall').classList.toggle('roomy',$('density').value==='roomy');$('close').onclick=close;viewer.addEventListener('cancel',e=>{e.preventDefault();close();});$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);$('variant').onclick=()=>{preview=!preview;paint();};$('reset').onclick=reset;$('plus').onclick=()=>changeZoom(.25);$('minus').onclick=()=>changeZoom(-.25);$('large').onload=shape;$('large').onerror=()=>$('status').textContent='Image unavailable. Try the original link.';
$('stage').addEventListener('wheel',e=>{e.preventDefault();changeZoom(e.deltaY<0?.25:-.25);},{passive:false});$('stage').ondblclick=()=>zoom>1?reset():changeZoom(1.2);
$('stage').onpointerdown=e=>{if(e.button!==0)return;$('stage').setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};};$('stage').onpointermove=e=>{if(!drag)return;pan={x:Math.max(-3000,Math.min(3000,drag.px+e.clientX-drag.x)),y:Math.max(-3000,Math.min(3000,drag.py+e.clientY-drag.y))};shape();};for(const n of ['pointerup','pointercancel','lostpointercapture'])$('stage').addEventListener(n,()=>drag=null);window.addEventListener('resize',shape);
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(!viewer.open){if(e.key==='/'){e.preventDefault();$('search').focus();}return;}if(['ArrowRight','ArrowLeft','+','=','-','0'].includes(e.key))e.preventDefault();if(e.key==='ArrowRight')step(1);if(e.key==='ArrowLeft')step(-1);if(['+','='].includes(e.key))changeZoom(.25);if(e.key==='-')changeZoom(-.25);if(e.key==='0')reset();});
function fromHash(){const id=location.hash.slice(1);if(items.some(a=>a.id===id))open(id,false);else if(viewer.open)close();}window.addEventListener('hashchange',fromHash);
$('share').onclick=async()=>{const url=location.origin+location.pathname+'#'+items[current].id;try{await navigator.clipboard.writeText(url);$('status').textContent='Picture link copied.';}catch{$('status').textContent=url;}};
$('verify').onclick=async()=>{const a=items[current];$('verify').disabled=true;$('status').textContent='Checking original bytes…';try{const r=await fetch(asset(a.original_url),{cache:'no-store'});if(!r.ok)throw Error('Original unavailable');const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await r.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==a.original_sha256)throw Error('Fingerprint mismatch');if(items[current]===a)$('status').textContent='Verified: original matches recorded SHA-256.';}catch(e){if(items[current]===a)$('status').textContent=e.message;}finally{$('verify').disabled=false;}};
try{const r=await fetch('catalog.json',{cache:'no-cache'});if(!r.ok)throw Error('Catalog unavailable');const data=await r.json();if(!Array.isArray(data.items)||data.items.length>500)throw Error('Invalid catalog');const ids=new Set();for(const a of data.items){if(typeof a.id!=='string'||ids.has(a.id)||typeof a.title!=='string'||typeof a.description!=='string'||typeof a.source_filename!=='string'||!/^[a-f0-9]{64}$/.test(a.original_sha256))throw Error('Invalid artwork entry');ids.add(a.id);asset(a.original_url);asset(a.preview_url);asset(a.thumbnail_url);if(a.cloudfront_original){const u=new URL(a.cloudfront_original);if(u.protocol!=='https:'||u.hostname!=='d2ol7oe51mr4n9.cloudfront.net'||u.search)throw Error('Unapproved media origin');}}items=data.items;for(const a of items){const b=document.createElement('button');b.dataset.id=a.id;b.setAttribute('aria-label',a.title);const im=document.createElement('img');im.src=asset(a.thumbnail_url);im.alt='';im.loading='lazy';b.append(im);b.onclick=()=>open(a.id);$('filmstrip').append(b);}filter();fromHash();document.body.dataset.catalogReady='true';}catch(e){$('count').textContent='Catalog unavailable. Original image links still work.';console.warn(e.message);}
