// Layout extension only. Original viewing, byte verification and source names stay in index.html.
const byId=id=>document.getElementById(id),cards=[...document.querySelectorAll('.card')];
const viewer=byId('viewer'),header=document.querySelector('header'),search=byId('search');
const label=search.closest('label');label.classList.add('browser-search');header.insertBefore(label,header.querySelector('nav'));
search.placeholder='Search names, places, source files…';
const controls=document.createElement('div');controls.className='filterbar';controls.setAttribute('aria-label','Picture filters');
for(const [name,query]of [['All pictures',''],['The Crossing','crossing'],['Gardens','garden']]){const b=document.createElement('button');b.textContent=name;b.dataset.query=query;b.setAttribute('aria-pressed',String(!query));b.onclick=()=>{search.value=query;search.dispatchEvent(new Event('input',{bubbles:true}));};controls.append(b);}
const densityLabel=document.createElement('label');densityLabel.textContent='Density';const select=document.createElement('select');select.id='browser-density';for(const [v,t]of [['dense','Dense'],['roomy','Roomy']]){const o=document.createElement('option');o.value=v;o.textContent=t;select.append(o);}select.onchange=()=>byId('grid').classList.toggle('roomy',select.value==='roomy');densityLabel.append(select);controls.append(densityLabel);byId('grid').before(controls);
search.addEventListener('input',()=>{for(const b of controls.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.query===search.value.trim().toLowerCase()));});
for(const card of cards){const im=card.querySelector('.picture img');const ratio=()=>{if(im.naturalWidth&&im.naturalHeight)card.style.setProperty('--ratio',String(im.naturalWidth/im.naturalHeight));};im.addEventListener('load',ratio);ratio();const id=document.createElement('span');id.className='browser-id';id.textContent=card.dataset.id+' · recorded display preview';card.querySelector('.copy').append(id);card.dataset.tags+=' '+card.querySelector('.picture').getAttribute('href').split('/').pop();}
const notes=document.createElement('details');notes.className='browser-notes';notes.id='browser-notes';const summary=document.createElement('summary');summary.textContent='Art yarn, image coverage & source receipts';notes.append(summary);document.querySelector('main').append(notes);for(const selector of ['.coverage','.yarn','.sources'])notes.append(document.querySelector(selector));
const more=document.createElement('a');more.href='browser-receipt.json';more.textContent='Image-browser change receipt ↗';notes.querySelector('.sources .links').append(more);
function openNotes(){if(['#yarn','#browser-notes'].includes(location.hash))notes.open=true;}document.querySelector('a[href="#yarn"]').addEventListener('click',()=>{notes.open=true;});openNotes();
viewer.classList.add('browser-viewer');const side=document.createElement('aside');side.className='viewer-side';side.setAttribute('aria-label','Artwork details and related pictures');const kind=byId('kind'),links=viewer.querySelector(':scope > .links'),details=viewer.querySelector(':scope > details'),status=byId('status');side.append(kind);const names=document.createElement('p');names.className='browser-file-label';side.append(names,links);const relatedTitle=document.createElement('h3');relatedTitle.className='browser-related-title';relatedTitle.textContent='Explore the same world';const hint=document.createElement('p');hint.className='browser-related-note';hint.textContent='Curated connections · not AI similarity search';const related=document.createElement('div');related.className='browser-related';side.append(relatedTitle,hint,related,details,status);viewer.append(side);
function sync(){document.body.classList.toggle('browser-viewing',viewer.open);if(!viewer.open)return;const active=cards.find(c=>new URL(c.querySelector('.picture').href).href===byId('original').href);if(!active)return;names.textContent='Gallery ID: '+active.dataset.id+'\nStored original: '+new URL(byId('original').href).pathname.split('/').pop();related.replaceChildren();for(const c of cards.filter(x=>x!==active)){const b=document.createElement('button');b.dataset.related=c.dataset.id;const im=document.createElement('img');im.src=c.querySelector('.picture img').src;im.alt='';const span=document.createElement('span');span.textContent=c.querySelector('h3').textContent;b.append(im,span);b.onclick=()=>c.querySelector('[data-open]').click();related.append(b);}}
new MutationObserver(sync).observe(byId('title'),{childList:true,subtree:true});new MutationObserver(sync).observe(viewer,{attributes:true,attributeFilter:['open']});sync();
// Direct picture links work both on initial load and when only the fragment changes.
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);const c=cards.find(x=>x.dataset.id===id);if(c)c.querySelector('[data-open]').click();else if(viewer.open)viewer.close();openNotes();});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!viewer.open&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){e.preventDefault();search.focus();}});
// Intentional: no tracking, external image search, remote upload, or private catalog embedding.
// Native modal focus can leave a just-disabled verification button; keep navigation available.
document.addEventListener('keydown',e=>{if(!viewer.open||e.defaultPrevented||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();byId(e.key==='ArrowRight'?'next':'previous').click();}});
