/** One cross-platform entry; built-ins only. Never serves private source or account state. */
import {readFile, writeFile, mkdir, readdir, stat, lstat, realpath, copyFile, rm} from 'node:fs/promises';
import {createServer} from 'node:http';
import {createHash} from 'node:crypto';
import {prepareWorlds} from './worlds.mjs';
import {privateEngine} from './peachfall-source.mjs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIRS = new Set(['anewgam-for-steven-cockpit','peachfall','goober','images','javascripts','stylesheets','shorts','shared','docs']);
const ROOT_FILES = new Set(['index.html','404.html','goober-release.json','params.json']);
// The preserved engine requests these three published images from the site root.
// Keep exact aliases; never expose a general source/ directory.
const PEACHFALL_IMAGE_ALIASES = [
  'source/images/anchors/01_gen22_page1_the_princess_who_could_not_leave_the_tower.png',
  'source/images/anchors/02_astral_assembly_sae_and_little_princesses.png',
  'source/images/anchors/03_gameplay_assume_her_fragments.png'
];
for (const alias of PEACHFALL_IMAGE_ALIASES) ROOT_FILES.add(alias);
const EXT = new Set(['.html','.css','.js','.mjs','.json','.webmanifest','.svg','.png','.jpg','.jpeg','.webp','.avif','.gif','.ico','.mp4','.webm','.mp3','.wav','.ogg','.woff','.woff2','.ttf','.txt','.md']);
const PRIVATE_SEGMENT = /^(?:\.|node_modules$|test-results$|playwright-report$|dist$)/;
const MIME = {'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webmanifest':'application/manifest+json','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.mp4':'video/mp4','.mp3':'audio/mpeg','.woff2':'font/woff2'};
export function publicPath(relative) {
  const parts = relative.split('/');
  if (!relative || parts.some(p => !p || PRIVATE_SEGMENT.test(p)) || relative.includes('\\')) return false;
  if (!(ROOT_FILES.has(relative) || DIRS.has(parts[0]) && parts.length > 1)) return false;
  if (/(?:\.test\.|\.spec\.|\.map$)/.test(relative)) return false;
  return EXT.has(path.extname(relative).toLowerCase());
}
async function filesUnder(root, relative = '') {
  const files = [];
  for (const entry of await readdir(path.join(root, relative), {withFileTypes:true})) {
    if (PRIVATE_SEGMENT.test(entry.name) || entry.isSymbolicLink()) continue;
    const rel = relative ? `${relative}/${entry.name}` : entry.name;
    if (entry.isDirectory()) files.push(...await filesUnder(root, rel));
    else if (entry.isFile()) files.push(rel);
  }
  return files.sort();
}
export async function prepare(root = ROOT) {
  await prepareWorlds(root);
  const files = (await filesUnder(path.join(root,'peachfall'))).filter(f => !['sw.js','offline-files.js'].includes(f) && publicPath(`peachfall/${f}`));
  const paths = ['./', ...files.map(f => './'+f), ...PEACHFALL_IMAGE_ALIASES.map(f => '../'+f), '../shared/ingress.js', '../shared/worlds.js', '../shared/ways.js', '../shared/ways.css', '../anewgam-for-steven-cockpit/colour-language.css', '../anewgam-for-steven-cockpit/icon-192.png', '../anewgam-for-steven-cockpit/icon-512.png'];
  const hash = createHash('sha256');
  let totalBytes = 0;
  for (const rel of paths.filter(x => x !== './')) {
    const bytes = await readFile(path.resolve(root, 'peachfall', rel));
    totalBytes += bytes.length; hash.update(rel).update(bytes);
  }
  hash.update(await readFile(path.join(root,'peachfall/sw.js')));
  const data = {version:hash.digest('hex').slice(0,20), files:paths, totalBytes};
  await writeFile(path.join(root,'peachfall/offline-files.js'), `/* Generated by npm run build/dev; do not edit. */\nself.__PEACHFALL_OFFLINE__ = ${JSON.stringify(data,null,2)};\n`);
  return data;
}
export async function build(root = ROOT) {
  const offline = await prepare(root);
  const output = path.join(root,'dist');
  // Only this fixed generated directory is replaced. It must not be a symlink.
  const existing = await lstat(output).catch(e => e.code === 'ENOENT' ? null : Promise.reject(e));
  if (existing?.isSymbolicLink()) throw new Error('Refusing to write through a dist symlink.');
  await rm(output,{recursive:true,force:true}); await mkdir(output,{recursive:true});
  const hashes = {};
  for (const rel of (await filesUnder(root)).filter(publicPath)) {
    await mkdir(path.dirname(path.join(output,rel)),{recursive:true});
    await copyFile(path.join(root,rel),path.join(output,rel));
    hashes[rel] = createHash('sha256').update(await readFile(path.join(output,rel))).digest('hex');
  }
  await writeFile(path.join(output,'build-receipt.json'),JSON.stringify({schema:'saelion-static-build-v1',files:hashes,peachfallOfflineVersion:offline.version,meaning:'Static file identity only; not deployment, DNS, AI, worker execution or accepted outcome.'},null,2)+'\n');
  return {files:Object.keys(hashes).length,offline};
}
export function serve(root = ROOT, port = 4317, preview = null) {
  const server = createServer(async (req,res) => {
    try {
      if (!['GET','HEAD'].includes(req.method)) {res.writeHead(405,{'Allow':'GET, HEAD'}); return res.end();}
      let decoded; try { decoded = decodeURIComponent((req.url || '/').split('?')[0]); } catch {res.writeHead(400);return res.end();}
      // Reject traversal before URL normalization and reject hidden/private paths even in local development.
      if (decoded.includes('\\') || decoded.includes('\0') || decoded.split('/').some(s => s === '..' || s.startsWith('.'))) {res.writeHead(403);return res.end();}
      let rel = decoded.replace(/^\/+/, '');
      if (!rel || rel.endsWith('/')) rel += 'index.html';
      if (preview) {
        const item = preview.routes.get('/'+rel);
        if (item) {
          res.writeHead(200,{'Content-Type':item.type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Robots-Tag':'noindex, nofollow','Content-Length':item.bytes.length});
          return res.end(req.method === 'HEAD' ? undefined : item.bytes);
        }
        // Never mix the selected engine with the historical public game or its SW.
        if (rel === 'peachfall' || rel === 'assets') {res.writeHead(308,{'Location':preview.launch});return res.end();}
        if (rel.startsWith('peachfall/') || rel.startsWith('assets/')) {res.writeHead(404);return res.end('Not in selected preview');}
      }
      let file = path.resolve(root,rel);
      if (!publicPath(rel)) {
        const candidate = rel + '/index.html';
        if (!publicPath(candidate) || !(await stat(path.join(root,candidate)).catch(()=>null))?.isFile()) {res.writeHead(404);return res.end('Not found');}
        res.writeHead(308,{'Location':'/'+rel+'/'});return res.end();
      }
      for (let i=1;i<=rel.split('/').length;i++) {
        if ((await lstat(path.join(root,...rel.split('/').slice(0,i)))).isSymbolicLink()) {res.writeHead(403);return res.end();}
      }
      const resolved = await realpath(file);
      if (!resolved.startsWith(path.resolve(root)+path.sep)) {res.writeHead(403);return res.end();}
      const content = await readFile(file);
      res.writeHead(200,{'Content-Type':MIME[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Length':content.length});
      res.end(req.method === 'HEAD' ? undefined : content);
    } catch(error) {res.writeHead(error.code === 'ENOENT' || error.code === 'EISDIR' ? 404 : 500);res.end('Unavailable');}
  });
  return new Promise((resolve,reject) => {server.once('error',reject);server.listen(port,'127.0.0.1',()=>resolve(server));});
}
async function main() {
  const command = process.argv[2] || 'doctor';
  const workspace = JSON.parse(await readFile(path.join(ROOT,'saelion.workspace.json'),'utf8'));
  if (command === 'build') {console.log(JSON.stringify(await build(),null,2));return;}
  if (command === 'dev' && process.argv.includes('--peachfall')) {
    const {selectedPreview} = await import('./peachfall-preview.mjs');
    const preview = await selectedPreview(ROOT,workspace.components.peachfall);
    const server = await serve(ROOT,4317,preview);
    console.log(`One home: http://127.0.0.1:${server.address().port}/\nSelected Peachfall: http://127.0.0.1:${server.address().port}${preview.launch}\nPrivate compiled snapshot; public files and saves unchanged. Not a published/offline release. Ctrl+C stops it.`);return;
  }
  if (command === 'dev') {await prepare(); const server = await serve(); console.log(`Saelion home: http://127.0.0.1:${server.address().port}/\nLive source files; refresh after editing. Ctrl+C stops this server.`);return;}
  if (command === 'doctor') {console.log(JSON.stringify(workspace,null,2));console.log('Remote AI / Saedo: NOT CONNECTED by this static site. Domain: NOT VERIFIED.');return;}
  if (command === 'source' || command === 'engine') {await privateEngine(command,ROOT,workspace.components.peachfall);return;}
  throw new Error('Use dev, build, doctor, source, or engine.');
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main().catch(error => {console.error(error.message);process.exitCode=1;});
